// Unit tests for src/provenance-prior.ts — V3_PLAN.md §E per-note prior.
//
// The function is pure, so these are pure unit tests: no fixtures, no git,
// no DB. Each test isolates one evidence rule, plus a combination test for
// the "Inbox + AI-watermark text" case the reweight code most cares about.

import { describe, expect, it } from "vitest";

import { priorVoice, type PriorVoiceInput } from "../src/provenance-prior.js";

const FLOAT_TOL = 1e-9;

/** Build an input with all-neutral defaults; tests override one axis at a time. */
function neutral(over: Partial<PriorVoiceInput> = {}): PriorVoiceInput {
  return {
    path: "some-note.md",
    ageDays: 100, // safely in the no-age-bump band (14 < age ≤ 365)
    frontmatterTags: [],
    bodyText: "",
    ...over,
  };
}

describe("priorVoice — base case", () => {
  it("is neutral (≈ 50/50) when no covariates fire", () => {
    const out = priorVoice(neutral());
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });
});

describe("priorVoice — folder evidence", () => {
  it("Resources/Concepts/ bumps durable", () => {
    const out = priorVoice(neutral({ path: "Resources/Concepts/Taste graph.md" }));
    expect(out.p_durable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeLessThan(0.5);
    // p_d=0.7, p_p=0.5, total=1.2 → 0.7/1.2 ≈ 0.5833
    expect(out.p_durable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("Resources/People/ bumps durable", () => {
    const out = priorVoice(neutral({ path: "Resources/People/John Milinovich.md" }));
    expect(out.p_durable).toBeGreaterThan(0.5);
    expect(out.p_durable).toBeCloseTo(0.65 / 1.15, 9);
  });

  it("Inbox/ bumps perishable", () => {
    const out = priorVoice(neutral({ path: "Inbox/random capture.md" }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.75 / 1.25, 9);
  });

  it("Sources/ bumps perishable", () => {
    const out = priorVoice(neutral({ path: "Sources/some-bookmark.md" }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.6 / 1.1, 9);
  });

  it("Journal/ bumps durable", () => {
    const out = priorVoice(neutral({ path: "Journal/2026-05-09.md" }));
    expect(out.p_durable).toBeGreaterThan(0.5);
    expect(out.p_durable).toBeCloseTo(0.6 / 1.1, 9);
  });
});

describe("priorVoice — age evidence", () => {
  it("ageDays > 365 bumps durable", () => {
    const out = priorVoice(neutral({ ageDays: 400 }));
    expect(out.p_durable).toBeGreaterThan(0.5);
    expect(out.p_durable).toBeCloseTo(0.6 / 1.1, 9);
  });

  it("ageDays < 14 bumps perishable", () => {
    const out = priorVoice(neutral({ ageDays: 7 }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.6 / 1.1, 9);
  });

  it("ageDays in the neutral band (14..365) does not bump either axis", () => {
    const out = priorVoice(neutral({ ageDays: 100 }));
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });
});

describe("priorVoice — frontmatter tag evidence", () => {
  it("'synthesis' tag bumps perishable", () => {
    const out = priorVoice(neutral({ frontmatterTags: ["synthesis"] }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'ai-summary' tag bumps perishable", () => {
    const out = priorVoice(neutral({ frontmatterTags: ["ai-summary"] }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("either tag among many still bumps perishable (single, not double)", () => {
    // Both tags present should still only bump once (the rule is OR'd).
    const out = priorVoice(neutral({ frontmatterTags: ["synthesis", "ai-summary", "concept"] }));
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("unrelated tags do not bump either axis", () => {
    const out = priorVoice(neutral({ frontmatterTags: ["concept", "design"] }));
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });
});

describe("priorVoice — body watermark evidence", () => {
  it("'generated by' watermark bumps perishable", () => {
    const out = priorVoice(neutral({ bodyText: "Generated by an automated pipeline." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'claude:' prelude watermark bumps perishable (no-space variant)", () => {
    const out = priorVoice(neutral({ bodyText: "claude:synthesis follows." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'claude: ' (space-after-colon, the most-common in-the-wild form) bumps perishable [v3.1 regex fix]", () => {
    // Pre-fix: trailing \b after `:` only matches when next char is word.
    // "claude: foo" has space after colon → no \b → no match. The fix drops
    // the trailing \b on the AI_WATERMARK_RE alternation. This test guards
    // the fix from regressing.
    const out = priorVoice(neutral({ bodyText: "claude: here is the synthesis." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'model id' watermark bumps perishable", () => {
    const out = priorVoice(neutral({ bodyText: "model id: claude-opus-4-7" }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'temperature N' watermark bumps perishable", () => {
    const out = priorVoice(neutral({ bodyText: "Settings: temperature 7, top_p 0.95." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("'GPT-N' watermark bumps perishable", () => {
    const out = priorVoice(neutral({ bodyText: "Compared against GPT-5 baseline." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("watermark match is case-insensitive", () => {
    const out = priorVoice(neutral({ bodyText: "GENERATED BY some bot, you know." }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.7 / 1.2, 9);
  });

  it("body without watermarks does not bump (negative case)", () => {
    // Short, lowercase, no AI tells, no formal opening sentence.
    const out = priorVoice(neutral({ bodyText: "just some quick thoughts" }));
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });
});

describe("priorVoice — formal-encyclopedia tone", () => {
  it("triggers on long capitalized opening sentence", () => {
    // Long capitalized sentence (>15 non-punct chars), period, then space.
    const text = "This is a comprehensive overview of taste graphs. The rest follows.";
    const out = priorVoice(neutral({ bodyText: text }));
    expect(out.p_perishable).toBeGreaterThan(0.5);
    expect(out.p_perishable).toBeCloseTo(0.55 / 1.05, 9);
  });

  it("does NOT trigger on normal lowercase prose", () => {
    // Lowercase opening, conversational.
    const text = "just some quick thoughts about the day, nothing formal here";
    const out = priorVoice(neutral({ bodyText: text }));
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });

  it("does NOT trigger on short capitalized sentence", () => {
    // Less than 15 non-punct chars between leading caps and the period.
    const text = "Hi there. Just a note.";
    const out = priorVoice(neutral({ bodyText: text }));
    expect(out.p_durable).toBeCloseTo(0.5, 9);
    expect(out.p_perishable).toBeCloseTo(0.5, 9);
  });
});

describe("priorVoice — combination", () => {
  it("Inbox + AI watermark + synthesis tag + fresh age = strongly perishable (> 0.7)", () => {
    // Stack folder evidence with content + tag + age evidence to exercise
    // the case the reweight code most cares about: an unstamped Inbox AI dump.
    const out = priorVoice({
      path: "Inbox/claude-dump-2026-05-09.md",
      ageDays: 3,
      frontmatterTags: ["synthesis"],
      bodyText: "Generated by claude-opus-4-7 on 2026-05-09.",
    });
    expect(out.p_perishable).toBeGreaterThan(0.7);
    expect(out.p_durable).toBeLessThan(0.3);
  });
});

describe("priorVoice — probability invariants", () => {
  // Use the same set of inputs across all invariant assertions so any future
  // covariate change has to keep the sum-to-1 property for every shape we test.
  const cases: Array<{ name: string; input: PriorVoiceInput }> = [
    { name: "neutral baseline", input: neutral() },
    { name: "Concepts folder", input: neutral({ path: "Resources/Concepts/X.md" }) },
    { name: "Inbox folder", input: neutral({ path: "Inbox/Y.md" }) },
    { name: "old age", input: neutral({ ageDays: 1000 }) },
    { name: "fresh age", input: neutral({ ageDays: 1 }) },
    { name: "synthesis tag", input: neutral({ frontmatterTags: ["synthesis"] }) },
    { name: "AI watermark body", input: neutral({ bodyText: "Generated by something." }) },
    {
      name: "all evidence pointing perishable",
      input: {
        path: "Inbox/Z.md",
        ageDays: 1,
        frontmatterTags: ["synthesis", "ai-summary"],
        bodyText: "Generated by claude-opus-4-7. Model id is claude-opus-4-7.",
      },
    },
    {
      name: "all evidence pointing durable",
      input: {
        path: "Resources/Concepts/A.md",
        ageDays: 1000,
        frontmatterTags: ["concept"],
        bodyText: "just a quick thought",
      },
    },
  ];

  for (const { name, input } of cases) {
    it(`p_durable + p_perishable === 1 for ${name}`, () => {
      const out = priorVoice(input);
      expect(out.p_durable + out.p_perishable).toBeCloseTo(1, 9);
      expect(out.p_durable).toBeGreaterThanOrEqual(0);
      expect(out.p_durable).toBeLessThanOrEqual(1);
      expect(out.p_perishable).toBeGreaterThanOrEqual(0);
      expect(out.p_perishable).toBeLessThanOrEqual(1);
      // Belt-and-suspenders: also assert with raw float tolerance.
      expect(Math.abs(out.p_durable + out.p_perishable - 1)).toBeLessThan(FLOAT_TOL);
    });
  }
});
