/**
 * Ecosystem config generator (P8-A4).
 *
 * Given the current `vaults` table, emit the PM2 `ecosystem.config.cjs`
 * CommonJS module that spawns one `grove-server-<slug>` + one
 * `grove-discovery-<slug>` process per vault, plus the shared
 * `grove-proxy` and `qmd-server`.
 *
 * Generation is deterministic and alphabetical-by-slug so `grove vault
 * create` produces a minimal diff each run. PLAN.md mandates a full
 * regenerate (no append) — this keeps the file auditable via git diff.
 */

import type Database from "better-sqlite3";

export interface VaultRow {
  id: string;
  slug: string;
  git_repo_path: string;
  server_port: number;
  discovery_port: number;
}

export interface EcosystemOptions {
  /** Absolute path on the VPS to the grove checkout (defaults to /root/grove). */
  repoRoot?: string;
  /** Proxy port (defaults to 8420). */
  proxyPort?: number;
  /** QMD port (defaults to 8177). */
  qmdPort?: number;
}

/**
 * Pull provisioned vaults (those with both ports set) from the DB, ordered
 * by slug. Only vaults that are fully provisioned show up — a vault row
 * without ports is a half-finished provision and shouldn't be spawned.
 */
export function readProvisionedVaults(db: Database.Database): VaultRow[] {
  return db
    .prepare(
      `SELECT id, slug, git_repo_path, server_port, discovery_port
         FROM vaults
        WHERE server_port IS NOT NULL AND discovery_port IS NOT NULL
        ORDER BY slug ASC`,
    )
    .all() as VaultRow[];
}

export function generateEcosystemConfig(
  vaults: VaultRow[],
  opts: EcosystemOptions = {},
): string {
  const repoRoot = opts.repoRoot ?? "/root/grove";
  const proxyPort = opts.proxyPort ?? 8420;
  const qmdPort = opts.qmdPort ?? 8177;

  const apps: Record<string, unknown>[] = [];

  // Proxy — one process, not vault-scoped.
  apps.push({
    name: "grove-proxy",
    script: `${repoRoot}/node_modules/.bin/tsx`,
    args: `${repoRoot}/src/proxy.ts`,
    env: {
      NODE_ENV: "production",
      GROVE_PORT: String(proxyPort),
      QMD_PORT: String(qmdPort),
    },
    autorestart: true,
    max_restarts: 10,
  });

  // QMD — one process, shared across vaults.
  apps.push({
    name: "qmd-server",
    script: `${repoRoot}/node_modules/.bin/qmd`,
    args: "serve",
    env: {
      NODE_ENV: "production",
      QMD_PORT: String(qmdPort),
    },
    autorestart: true,
    max_restarts: 10,
  });

  for (const v of vaults) {
    apps.push({
      name: `grove-server-${v.slug}`,
      script: `${repoRoot}/node_modules/.bin/tsx`,
      args: `${repoRoot}/src/server.ts`,
      env: {
        NODE_ENV: "production",
        GROVE_VAULT: v.git_repo_path,
        GROVE_VAULT_ID: v.id,
        GROVE_SERVER_PORT: String(v.server_port),
      },
      kill_timeout: 60_000,
      autorestart: true,
      max_restarts: 10,
    });
    apps.push({
      name: `grove-discovery-${v.slug}`,
      script: `${repoRoot}/node_modules/.bin/tsx`,
      args: `${repoRoot}/src/discovery-worker.ts`,
      env: {
        NODE_ENV: "production",
        GROVE_VAULT: v.git_repo_path,
        GROVE_VAULT_ID: v.id,
        GROVE_DISCOVERY_PORT: String(v.discovery_port),
      },
      autorestart: true,
      max_restarts: 10,
    });
  }

  const body = JSON.stringify({ apps }, null, 2);
  return `/**
 * Grove PM2 ecosystem — GENERATED by scripts/vault-provision + ecosystem-gen.ts.
 * Re-generated on every \`grove vault create\`. Do not edit by hand — your changes
 * will be overwritten on the next provision.
 */
module.exports = ${body};
`;
}
