// Per-note voice prior for legacy-unknown (unstamped) notes.
//
// V3_PLAN.md §E. Used by hybrid-search.ts reweight to softly blend voice
// factors for notes whose introducing commit has no Provenance-* trailer,
// instead of treating every unstamped note identically.
//
// The covariate weights below are HAND-CODED PRIORS, not fit weights —
// the labeled population today is 183 perishable notes + 0 durable notes
// (Phase B3 backfill of durables hasn't happened), so we cannot fit a
// `p_durable` axis until B3 lands. Once it does, the weights here become
// trainable; a cron worker will rewrite them into runtime_config and this
// module will load from there.
//
// Inputs are cheap, deterministic, no LLM. Folder + age + frontmatter tags
// + AI-watermark text in the body.

export interface PriorVoiceInput {
  /** Vault-relative path. Used for folder-evidence rules. */
  path: string;
  /**
   * Days since the note's age signal. Caller's responsibility to pass
   * either segment.written_at (blame fallback) or first-commit date —
   * see V3_PLAN.md §E "Age source" note for why this is caller-decided.
   */
  ageDays: number;
  /** Parsed frontmatter tags (empty array if none). */
  frontmatterTags: string[];
  /** Note body text — MUST NOT include the frontmatter block. */
  bodyText: string;
}

export interface PriorVoice {
  /** Estimated probability the note is durable. */
  p_durable: number;
  /** Estimated probability the note is perishable. */
  p_perishable: number;
}

// AI-watermark patterns — text strings frequently emitted by AI agents
// when they ramble about their own pipeline (citations of model id,
// "generated by", "claude:" preludes, etc.). Case-insensitive.
const AI_WATERMARK_RE = /\b(generated by|claude:|model id|temperature \d|GPT-\d)\b/i;

// Formal-encyclopedia tone heuristic — a note that opens with a long,
// capitalized, period-terminated sentence is more likely to be machine
// summary than human stream-of-thought. Applied to first 200 chars only.
const FORMAL_TONE_RE = /^[A-Z][^.!?]{15,}\.\s+/m;

/**
 * Per-note voice prior for legacy-unknown (unstamped) notes.
 *
 * Hand-coded priors per V3_PLAN.md §E — see file header for why these
 * aren't fit weights yet. Returns probabilities normalized so
 * `p_durable + p_perishable === 1` (within float tolerance).
 *
 * Pure function. No I/O, no DB access, no side effects.
 */
export function priorVoice(input: PriorVoiceInput): PriorVoice {
  const { path, ageDays, frontmatterTags, bodyText } = input;

  let p_d = 0.5; // base prior
  let p_p = 0.5;

  // Folder evidence
  if (path.startsWith("Resources/Concepts/")) p_d += 0.2;
  if (path.startsWith("Resources/People/")) p_d += 0.15;
  if (path.startsWith("Inbox/")) p_p += 0.25;
  if (path.startsWith("Sources/")) p_p += 0.10;
  if (path.startsWith("Journal/")) p_d += 0.10;

  // Age evidence
  if (ageDays > 365) p_d += 0.10;
  if (ageDays < 14) p_p += 0.10;

  // Frontmatter tag evidence
  if (frontmatterTags.includes("synthesis") || frontmatterTags.includes("ai-summary")) {
    p_p += 0.20;
  }

  // Body text evidence — AI watermark strings
  if (AI_WATERMARK_RE.test(bodyText)) p_p += 0.20;
  // Formal-encyclopedia tone — only inspect the first 200 chars
  if (FORMAL_TONE_RE.test(bodyText.slice(0, 200))) p_p += 0.05;

  // Normalize so the pair sums to 1.
  const total = p_d + p_p;
  return {
    p_durable: p_d / total,
    p_perishable: p_p / total,
  };
}
